services:
  backend:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/hairbnb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=123456
    depends_on:
      - db
  db:
    image: postgres:15.4
    ports:
      - 5432:5432
    volumes:
      - hairbnb:/data/db
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: admin
      POSTGRES_DB: hairbnb

volumes:
  hairbnb: