server:
  port: 8080

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/hairbnb"
    username: "admin"
    password: "123456"
#    driver-class-name:

app:
  jwt:
    secret: "61DC8E91921C25314AE714486E5EA"
    ttl: 1d
