server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/hairbnb}
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:123456}
  redis:
    host: localhost
    port: 6379

app:
  jwt:
    secret: ${JWT_SECRET:9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9}
    expiration: 1d
    refresh-expiration: 7d

rate-limiter:
  bucket-capacity: 100
  refill-rate: 10
  refill-period: 1s

logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR
logging.level.org.springframework.security: TRACE
